import { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import Header from '../components/Header';
import Footer from '../components/Footer';

export const metadata: Metadata = {
    title: ' Book Buddy  ',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <title>{metadata?.title as string}</title>
            <meta name="description" content={metadata?.description as string} />
            <meta
          name="keywords"
        //   content={(metadata?.keywords as string[]).join(", ")}
        />
            <body className="">
                <ThemeProvider attribute="class" defaultTheme="system">
                    <Header />
                    <main className="relative overflow-hidden"></main>
                    {children}
                </ThemeProvider>
                <Footer />
            </body>
        </html>
    );
}
