import { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import FirebaseTest from '@/src/components/FirebaseTest';
export const metadata: Metadata = {
    title: ' Book Buddy  ',
    description: 'Generated by create next app',
    keywords: ['']
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <title>{metadata?.title as string}</title>
            <meta
                name="description"
                content={metadata?.description as string}
            />
            <meta
                name="keywords"
                //   content={(metadata?.keywords as string[]).join(", ")}
            />
            <body className="">
                <ThemeProvider attribute="class" defaultTheme="system">
                    {children}
                    <FirebaseTest />
                </ThemeProvider>
            </body>
        </html>
    );
}
